

services:
  # Service MongoDB
  mongo:
    image: mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db 

  # Service Backend
  backend:
    build: ./backend
    ports:
      - "3001:3001" 
    depends_on:
      - mongo 

  # Service Frontend
  frontend:
    build: ./frontend
    ports:
      - "8080:80" 
    depends_on:
      - backend 


volumes:
  mongo-data:  
